### ISSUE TITLE
Homepage scroll view

### ISSUE THREAD

**Issue by dustmarijn** [dustmarijn/Corona-Data-App#45]
Je kan op de homepage niet scrollen, dit is een probleem als je niet zon groot scherm hebt

@weshakvoort kan jij nog een screenshot toevoegen?

**Comment by weshakvoort** [comment]
![image](https://user-images.githubusercontent.com/70153169/113264654-80b48100-92d3-11eb-8eeb-deac8ce5cd7a.png)

**Comment by Jensbouma123** [comment]
Ik heb een fix er voor en kan hier van eventueel een Pull Request van maken. Er wordt dan niet zoveel gepusht. Is dat goed?
